Fix division with int and float (#18)
When compiling the project on my Linux machine I encountered the
following error:

```
Error compiling shader at res/shaders/chunk.vs:
0(34) : error C1020: invalid operands to "/"
0(35) : error C1020: invalid operands to "/"
0(37) : error C1020: invalid operands to "/"
0(37) : error C1020: invalid operands to "/"
0(39) : error C1020: invalid operands to "/"
```

The operands are now all converted to floats and the shader compiles.